server:
  servlet:
    context-path: /coffeemachine
  port: 8080

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:coffee_machine}
    username: ${DB_USERNAME:miracle}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  baseline-on-migrate: true
  enabled: true